"""add field last_message_id in conversation model

Revision ID: 729b2ab268e5
Revises: 68647f8db4a4
Create Date: 2026-03-12 13:21:18.110887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '729b2ab268e5'
down_revision: Union[str, Sequence[str], None] = '68647f8db4a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'message', ['last_message_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_message_id')

    # ### end Alembic commands ###
