"""add conversation group model

Revision ID: 8c49bbba3ff5
Revises: 729b2ab268e5
Create Date: 2026-03-13 15:32:23.830380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8c49bbba3ff5'
down_revision: Union[str, Sequence[str], None] = '729b2ab268e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversationgroup',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('group_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_group_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    with op.batch_alter_table('conversationgroup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversationgroup_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_created_by'))
        batch_op.drop_index(batch_op.f('idx_conversation_last_message'))
        batch_op.create_index('idx_conversation_last_message', [sa.literal_column('last_message_at DESC')], unique=False)
        batch_op.drop_constraint(batch_op.f('conversation_created_by_fkey'), type_='foreignkey')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.create_index('idx_friend_friend', ['friend_id'], unique=False)
        batch_op.create_index('idx_friend_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_index('idx_friend_user')
        batch_op.drop_index('idx_friend_friend')

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('conversation_created_by_fkey'), 'user', ['created_by'], ['id'])
        batch_op.drop_index('idx_conversation_last_message')
        batch_op.create_index(batch_op.f('idx_conversation_last_message'), ['last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('conversationgroup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversationgroup_created_by'))

    op.drop_table('conversationgroup')
    # ### end Alembic commands ###
