"""add ondelete in last message id

Revision ID: 95cfea1d95ea
Revises: b94216540224
Create Date: 2026-03-14 05:38:48.622766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95cfea1d95ea'
down_revision: Union[str, Sequence[str], None] = 'b94216540224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conversation_last_message_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'message', ['last_message_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversation_last_message_id_fkey'), 'message', ['last_message_id'], ['id'])

    # ### end Alembic commands ###
