"""rename column in user model

Revision ID: a0469fcc6bf5
Revises: 95cfea1d95ea
Create Date: 2026-03-17 08:47:32.878848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0469fcc6bf5'
down_revision: Union[str, Sequence[str], None] = '95cfea1d95ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_message_conversation_created_desc'))
        batch_op.create_index('idx_message_conversation_created_desc', ['conversation_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)

    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column(
            "displayed_name",
            new_column_name="display_name"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as batch_op:
        batch_op.alter_column(
            "display_name",
            new_column_name="displayed_name"
        )

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('idx_message_conversation_created_desc')
        batch_op.create_index(batch_op.f('idx_message_conversation_created_desc'), ['conversation_id', sa.literal_column('created_at DESC')], unique=False)

    # ### end Alembic commands ###
