"""add coversation participant index

Revision ID: b94216540224
Revises: 8c49bbba3ff5
Create Date: 2026-03-14 05:05:59.139167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b94216540224'
down_revision: Union[str, Sequence[str], None] = '8c49bbba3ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversationparticipant', schema=None) as batch_op:
        batch_op.create_index('idx_conv_participants', ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversationparticipant', schema=None) as batch_op:
        batch_op.drop_index('idx_conv_participants')

    # ### end Alembic commands ###
