"""rename column in ConversationGroup model

Revision ID: e05e0d1c90cd
Revises: a0469fcc6bf5
Create Date: 2026-03-17 09:59:06.339435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e05e0d1c90cd'
down_revision: Union[str, Sequence[str], None] = 'a0469fcc6bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversationgroup") as batch_op:
        batch_op.alter_column(
            "group_name",
            new_column_name="name"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversationgroup") as batch_op:
        batch_op.alter_column(
            "name",
            new_column_name="group_name"
        )

    # ### end Alembic commands ###
